#!/bin/sh
# FreeLinX openbox autostart helper

GLOBALAUTOSTART=/etc/xdg/openbox/autostart
AUTOSTART="${XDG_CONFIG_HOME:-"$HOME/.config"}/openbox/autostart"



if test -f "$AUTOSTART"; then
    sh "$AUTOSTART"
elif test -f "$AUTOSTART.sh"; then
    sh "$AUTOSTART.sh"
elif test -f "$GLOBALAUTOSTART"; then
    sh "$GLOBALAUTOSTART"
elif test -f "$GLOBALAUTOSTART.sh"; then
    sh "$GLOBALAUTOSTART.sh"
fi
