#!/bin/sh
# FreeLinX openbox autostart helper

GLOBALAUTOSTART=/etc/xdg/openbox/autostart
AUTOSTART="${XDG_CONFIG_HOME:-"$HOME/.config"}/openbox/autostart"

if command -v xsetroot >/dev/null 2>&1; then
    xsetroot -solid "#4c6b73" 2>/dev/null
fi

if test -f "$AUTOSTART"; then
    sh "$AUTOSTART"
elif test -f "$AUTOSTART.sh"; then
    sh "$AUTOSTART.sh"
elif test -f "$GLOBALAUTOSTART"; then
    sh "$GLOBALAUTOSTART"
elif test -f "$GLOBALAUTOSTART.sh"; then
    sh "$GLOBALAUTOSTART.sh"
fi
