# /etc/doas.conf: FreeLinX Privilege Elevation Rules
# SPDX-License-Identifier: ISC
#
# Syntax: permit|deny [options] identity [as target] [cmd command [args ...]]
# Members of the 'wheel' group can run commands as root.

permit persist :wheel

# Allow passwordless system power control and hardware management for wheel
permit nopass :wheel cmd reboot
permit nopass :wheel cmd poweroff
permit nopass :wheel cmd zzz
permit nopass :wheel cmd ZZZ
permit nopass :wheel cmd flxpower
permit nopass :wheel cmd flxdriver
