general {
    output_format = "none"
    colors = false
    interval = 1
    color_good = "#00ff00"
    color_degraded = "#ffff00"
    color_bad = "#ff0000"
}

order += "cpu_usage"
order += "load"
order += "memory"
order += "disk /"
order += "time"

cpu_usage {
    format = "CPU %usage"
}

load {
    format = "LOAD %1min"
}

memory {
    format = "MEM %percentage_used"
}

disk "/" {
    format = "DISK %percentage_used (%free)"
}

time {
    format = "%a %Y-%m-%d %H:%M:%S"
}